### ISSUE TITLE
Define type for user does nothing

### ISSUE THREAD

**Issue by letoast** [trandaison/nuxt-3-auth#13]
Trying to extend the type definition for User according to the docs does nothing: https://nuxt-3-auth.github.io/guide/typescript.html

the type is still `any`

**Comment by trandaison** [comment]
@letoast 
Fixed and released in `v0.0.16`, make sure you check the [docs](https://nuxt-3-auth.github.io/guide/typescript.html) as well. Thanks for reporting!
