### ISSUE TITLE
Disable the built-in /login?

### ISSUE THREAD

**Issue by Stiropor** [trandaison/nuxt-3-auth#14]
Is it possible to somehow completely remove the /login from package? I have the same route and would like to use my own form that is styled like the rest of website.

**Comment by trandaison** [comment]
Hi @Stiropor
There is no way to completely remove the `/login` page yet. However, if you want to use your own login page, you can override the `routes` option like this
```ts
// nuxt.config.ts
import { resolve } from 'pathe';

export default defineNuxtConfig({
  auth: {
    routes: {
      login: {
        name: 'login',
        file: resolve(__dirname, './pages/login.vue'),
        path: '/login',
      },
    },
  },
});
```
Please note that don't change the `name: 'login'` property. You can resolve any page component for the login page, or change the login path (to `/sign-in`, for example`)

**Comment by Stiropor** [comment]
Thank you, @trandaison, I saw this options but somehow thought it'd still be using your component.
