### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by paulvonber** [trandaison/nuxt-3-auth#16]
Any suggestion what could cause of getting this error message?
It seems it's related to refresh token, but I'm not getting why jwtDecode is trying to decode refresh_token. 

`Invalid token specified: missing part #2`
<img width="642" alt="image" src="https://github.com/trandaison/nuxt-3-auth/assets/37245111/a29b40e8-7a1b-43de-870c-b507560bbc0f">

**Comment by trandaison** [comment]
Hi @paulvonber
There is a limitation so far, it requires to use jwt tokens (also mentioned on the [docs](https://nuxt-3-auth.github.io/prerequisites.html#api-server)). If your token is not a jwt one will cause this error.
In fact, I am planning to support any type of token soon. Can you switch to JWT tokens until then if possible? Or any PR are welcome.

**Comment by paulvonber** [comment]
> Hi @paulvonber
> 
> There is a limitation so far, it requires to use jwt tokens (also mentioned on the [docs](https://nuxt-3-auth.github.io/prerequisites.html#api-server)). If your token is not a jwt one will cause this error.
> 
> In fact, I am planning to support any type of token soon. Can you switch to JWT tokens until then if possible? Or any PR are welcome.

Thanks, yeah I've realised that you need jwt in order to get expiry date of the refresh token, would be quite nice to have manually added maxAge in config 😌

**Comment by trandaison** [comment]
@paulvonber non-jwt tokens are now supported from [v0.1.1](https://github.com/trandaison/nuxt-3-auth/releases/tag/v0.1.1), give it a try and let me know if you have any problem.
