### ISSUE TITLE
Value is missing on SSR

### ISSUE THREAD

**Issue by paulvonber** [trandaison/nuxt-3-auth#19]
Can you please clarify why I can't get `loggedIn.value` on SSR is this intended behaviour?

here is how my code looks like:
```
  const { $auth } = useNuxtApp()
  const { user, loggedIn } = $auth

  if (import.meta.server) {
    console.log(`🆘 ~ SERVER loggedIn:`, loggedIn)
    console.log(`🆘 ~ SERVER loggedIn:`, loggedIn.value)
  }

  if (import.meta.client) {
    console.log(`🆘 ~ CLIENT loggedIn:`, loggedIn)
    console.log(`🆘 ~ CLIENT loggedIn:`, loggedIn.value)
  }
```

And here is the result:
SSR:
<img width="745" alt="image" src="https://github.com/trandaison/nuxt-3-auth/assets/37245111/e61f4f18-cb97-474f-ba28-62fe6c41b821">

CLIENT:
<img width="738" alt="image" src="https://github.com/trandaison/nuxt-3-auth/assets/37245111/eb28c1f3-a2b6-4334-8836-3eeb403a12a2">

**Comment by trandaison** [comment]
@paulvonber Can you create a reproduce repo on codesandbox or stackblitz?
It seem something's wrong with your code, I'm testing on local but the SSR works just fine.

### The component 
![Screenshot 2024-06-24 at 08 39 11](https://github.com/trandaison/nuxt-3-auth/assets/13447235/1349b58c-9f49-4243-82aa-e58a8193407b)

### The debug log on server side

<img width="714" alt="Screenshot 2024-06-24 at 08 38 51" src="https://github.com/trandaison/nuxt-3-auth/assets/13447235/1d6a4dd8-da67-4e4d-8a37-481482663972">

![Screenshot 2024-06-24 at 08 38 35](https://github.com/trandaison/nuxt-3-auth/assets/13447235/f28ce634-6dcd-4f0a-b6ed-b1ffc4cb953a)

### The SSR content
![Screenshot 2024-06-24 at 08 38 15](https://github.com/trandaison/nuxt-3-auth/assets/13447235/70f13ec2-6b8d-4ecf-9bde-1f801dabb08b)

**Comment by paulvonber** [comment]
@trandaison I'll try to find a time to create repro as this is a bit of things to do. 
But would you try out to get the value within the middleware as I have problem there in the page/component everything works correctly for me as well.

**Comment by trandaison** [comment]
@paulvonber The same result. 

<img width="1049" alt="Screenshot 2024-06-24 at 21 04 52" src="https://github.com/trandaison/nuxt-3-auth/assets/13447235/066587bc-ed89-4e55-b240-3a79eaa7147b">
<img width="698" alt="Screenshot 2024-06-24 at 21 03 20" src="https://github.com/trandaison/nuxt-3-auth/assets/13447235/af68909b-4fe0-43d8-a978-80472f98ab3c">
<img width="1440" alt="Screenshot 2024-06-24 at 21 02 20" src="https://github.com/trandaison/nuxt-3-auth/assets/13447235/7d57bdc1-1163-4719-8be1-7796f9d2c058">

Did you set `auth.middleware.global = false` in the `nuxt.config.ts` file?

**Comment by paulvonber** [comment]
I do have ` auth.middleware.global = true ` not sure if that anyhow clashes, but I also try to use it in `middleware_name.global.js` so globally as well.

**Comment by trandaison** [comment]
I got it. Your middleware is a global one, and it has a higher order than the `auth` middleware, so it executes before the `auth` middleware where I put the logic to determine the login session.

I will fix in the next release. Thanks for the support!

**Comment by trandaison** [comment]
@paulvonber This issue is related to an nuxt issue here: https://github.com/nuxt/nuxt/issues/27932
It was fixed however it will be release in the next major version (v4.0.0), after v4 is released, this issue will be fix on nuxt-3-auth.
