### ISSUE TITLE
refreshToken and maxAge

### ISSUE THREAD

**Issue by Stiropor** [trandaison/nuxt-3-auth#20]
I see that only for JWT tokens this package will look at `exp` value otherwise we need to set it ourselves. Is it possible somehow to set/change programaticali after login? I get `expiresAt` data from some API and would like to set the maxAge of refreshToken to expiresAt - 30 seconds, so I can call refresh before it actually expires. I need to make user's token not to expire in case someone is entering data/text on a page too long.

**Comment by trandaison** [comment]
@Stiropor In that case, you don't know how many seconds is enough, 30s or 2 min or any other value... could not be enough, I guess.
Instead, you can check if `$auth.accessToken()` exists before you perform an action, if it does not exist, you can call `$auth.refreshTokens()` first, then submit the form.

However, nuxt-3-auth support this out of the box, as long as the refresh token is still valid, when the access token expires and response 401, it will perform a refresh token request automatically, then retry the original request. You don't have to care about the token expires.
