### ISSUE TITLE
Error when trying to use the package in nuxt app

### ISSUE THREAD

**Issue by enzortk** [trandaison/nuxt-3-auth#25]
I set the options in nuxt.config.ts like this

```
 auth: {
    endpoints: {
      baseUrl: process.env.NUXT_PUBLIC_API_BASE_URL,
      login: { url: 'auth/login', method: 'POST', property: 'data' },
      logout: { url: 'auth/logout', method: 'DELETE' },
      refresh: { url: 'auth/refresh-token', method: 'POST', property: 'data' },
      user: { url: 'auth/me', method: 'GET', property: 'data' },
      // signup: { url: 'auth/register' },
    },
    middleware: { global: true },
    token: {
      headerName: 'Authorization',
      type: 'Bearer',
    },
    refreshToken: {
      paramName: 'token',
    },
  },
```

but when I run the app, console shows this error 

`nuxt.js?v=a9160863:122 [nuxt] error caught during app initialization 
TypeError: Cannot read properties of undefined (reading 'hasTokens')
    at authMiddleware (auth.mjs?v=a9160863:19:28)`

Seems the $auth object is undefined at that point of the code, any idea of what is wrong with the config ?

**Comment by trandaison** [comment]
@enzortk Can you create a reproduction repo on [stackblitz.com](https://stackblitz.com/github/nuxt/starter/tree/v3)?

**Comment by enzortk** [comment]
> @enzortk Can you create a reproduction repo on [stackblitz.com](https://stackblitz.com/github/nuxt/starter/tree/v3)?

Ok! give me some time and I'll share the link

**Comment by amery** [comment]
this error happens after https://github.com/trandaison/nuxt-3-auth/issues/39 in the console log
